CREATE DATABASE IF NOT EXISTS control DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE control;

CREATE TABLE IF NOT EXISTS nodos (
    id UUID NOT NULL DEFAULT UUID_V7() PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    mac VARCHAR(50) NOT NULL UNIQUE
)ENGINE = InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE USER IF NOT EXISTS 'control'@'%' IDENTIFIED BY 'iot2026';
GRANT SELECT, INSERT, UPDATE, DELETE ON `control`.* TO 'control'@'%';
